### PR TITLE
Added wss dialing

### PR DESCRIPTION
**Pull request by Jorropo**
This pr is a duplicate of #15 because it seems dead.
~~I chosed to only allow connection from dnsaddr (and dns4 and dns6) because wss is for browser and bypass mixed content error, so I recreated this so users will not get confused by working with go-ipfs and not in browser.~~
*That require an useless work and complexification of libp2p and libp2p-swarm so that was aborted.*

~~Also certificates came from system and is currently is only avaible on *nix due to a bug in golang's crypto/x509 library. The code need no change when the bug will be fixed to be windows compatible (just recompile). So on windows certificates will not be loaded and tls connection will be made even if certificate is wrong.~~
*That not a bug anymore because this fonctionality isn't anymore.*
## To do :
- [X] Implementation
- [ ] Add some test
  - [X] Parsing
  - [ ] Connection
- [ ] Test in real condition
  - [ ] libp2p
  - [ ] ipfs
- [ ] Add a small docs about reverse proxy
## Fix :
- [x] Fix the bug disabling wss when SSL certificate is not avaible by disabling SSL verification in this case.
- [ ] ~~Fix the bug making dns4 and dns6 like dnsaddr (currently its ignoring 4 and 6 and just taking the host)~~
## Potential future upgrade :
- Verify tls certificate of connection. (useless for security but good for minor compatibility with js-libp2p)
- Allow listen by generating a random certificate. (useless and will create some fake hope by browser peer and slow them down in their discovery of the network, only usefull with next point)
- Generate an TLS certificate for listening by derivating the libp2p private key with `websocket-secure` or wss protocol code and the host to have a constant one. (doesn't add more config for user, allow to **not** use a reverse proxy but still require manual approval of certificate)

### CODE REVIEW

**Comment by Stebalien** [comment]
We usually resolve dnsaddrs at a higher layer so I'm not sure if this will work without some tweaks to go-libp2p and go-libp2p-swarm. However, I may be wrong.

**Comment by Jorropo** [comment]
@Stebalien I havn't tested this yet but I'm sure there will be no problem with resolving because from my test `a.ValueForProtocol(p[0].Code)` return either the ip or the domain.
Maybe I'll have to tweak with tls connection (with a manual resolving).

**Comment by Stebalien** [comment]
> Edit:

Unfortunately, that's what we do, IIRC. However, we _may_ record both...

---

Regardless, I believe you're looking for `/dns4` and `/dns6`, not `/dnsaddr`.

**Comment by Jorropo** [comment]
@Stebalien 
> Regardless, I believe you're looking for /dns4 and /dns6, not /dnsaddr.

Actualy i'm looking for any of these, the librairy just use the domain and resolve it after.
And you makes me thinked I have to limit to ip4 if dns4 is used and same for v6.

**Comment by Stebalien** [comment]
dnsaddr works a bit differently. Given `/dnsaddr/foobar.com/ipfs/QmPeer`, we lookup for TXT records of the form `dnsaddr=/.../ipfs/QmPeer` on the `_dnsaddr.foobar.com` domain. That allows us to specify the port and transport inside the DNS record as well.

Unfortunately, that means that converting `/dnsaddr/foobar.com/tcp/123` to `wss://foobar.com:123`.

---

For now, I think the simplest solution is to specify the TLSClientConfig websocket option and pass in a TLS config with `InsecureSkipVerify` set to true. We're not relying on this for security anyways.

**Comment by Jorropo** [comment]
@Stebalien today I tryed to make it works with go-libp2p-example, and after a long time of learning what is mod I finaly get it to not work :(.
I followed your advice but an other problem shown, host of http 1.1.
Currently the server endpoint is on <http|ws[s]>://0.0.0.0/ wich makes a problem because if we use IP we can't send the host parameter to request on anything other than default.
But on my default web server index page I have somethings important and I don't wont to throw it.
(I originaly thinked creating a new domain ipfspeer.jorropo.ovh with a cname to my server and use vhost, but without the dns<4|6> I can't do that).

So I think we should rewrite ws[s] addrs like that :
```
/<ip|dns><4|6>/<enter here domain or ip>/ws[s]/<enter here endpoint>
```
Also old address like that would still work and just use / as endpoint :
```
/<ip|dns><4|6>/<enter here domain or ip>/ws[s]
```
This just have one draw back, you can only register endpoint under / and not in ipfs/endpoint if you would due to MA limitation (except if you can escape / in ma, in this case I'm interested about that).

That should be very easy (that a line to change in the dial part and one line in the listen part).
But I can't actualy figure out how to register a protocol with a parameters, I have looked go-tcp-transport and I doesn't see any transport registering in the repo so I guess this one is special and preregistered.
And I also looked go-utp-transport, here I clearly see where the protocol is registered but I don't see somethings very different explaining how to pass a param.

So how can I add an string endpoint params to ws[s] and do `a.ValueForProtocol(p[2].Code)` ?

**Comment by raulk** [comment]
This PR attempted to take #15 over the finish line, but was ultimately superseded by #72, which 0x has deployed in production.

**Pull request closed without merging**
