### PR TITLE
Add WebAssembly support and the ability to Dial from browsers

### PR DESCRIPTION
**Pull request by Stebalien**
Rebased https://github.com/libp2p/go-ws-transport/pull/51 with:

* passing tests
* the remaining concerns addressed 

(see the last 4 commits for actual changes)

### CODE REVIEW

**Comment by albrow** [comment]
@Stebalien looks good at a glance. I should have time to do some testing on our end next week (after Devcon).

**Comment by Stebalien** [comment]
Thanks!

**Comment by albrow** [comment]
@Stebalien sorry for the late reply. I can confirm that after updating our code to include these changes, our integration tests still pass. Thanks for your help implementing this 😄 .

**Comment by Stebalien** [comment]
Awesome!

**Pull request merged**
