### PR TITLE
add instrumentation for debugging concurrent writes

### PR DESCRIPTION
**Pull request by vyzo**
See #56

### CODE REVIEW

**Comment by Jorropo** [comment]
You would this to be executed each time ? I think it should be only in debug condition.

**Comment by vyzo** [comment]
This is a temporary patch to help identify the problem.

**Comment by Jorropo** [comment]
I don't think there is need to mege, but thx, I'll compile it and run it for my node.

**Comment by Stebalien** [comment]
@Jorropo (there's no intention to merge this)

**Comment by vyzo** [comment]
mutex merged in #65.

**Pull request closed without merging**
